### ISSUE TITLE
Misleading tutorial for next-auth integration with ms graph lib

### ISSUE THREAD

**Issue by ricardasjak** [microsoft/MicrosoftCloud#26]
I have followed [nextjs auth tutorial ](https://microsoft.github.io/MicrosoftCloud/tutorials/docs/Authentication-App-With-NextJs-And-Microsoft-Graph/), which title states there is integration with `@microsoft/microsoft-graph-client` package. I think this is wrong and misleading, because actually tutorial is all about next-auth integration with azure-ad, and there is no dependency code on MS Graphs library and no dependency on MS Teams (which is stated at the beginning of this tutorial).

I googled this tutorial, because I was looking how to integrate MS Teams with Nextjs (next-auth).
There is big chance, I am wrong somewhere, I would appreciate some clarification then.

**Comment by glaucia86** [comment]
Hi @ricardasjak. How are you? You can see the usage of  `@microsoft/microsoft-graph-client` in the second tutorial (Reminder App). I decided to divide it into two parts, because this tutorial is more dedicated to students and not for Pro-Developers. Therefore, to help the development of beginners people, I decided to divide the tutorial into 2 parts.

I may be changing the title to Part 01 and Part 02. I think it would actually avoid confusion in the textual interpretation of the developed workshops.

You can follow usage of `@microsoft/microsoft-graph-client` in that file here:

https://github.com/glaucia86/msgraph-nextjs-workshops/blob/main/demo-02/reminder-app/pages/api/getPresence.ts

I apologize in advance for the confusion in the title. However, it is not misleading. The use of the word sounded very strong to me here in this context.

If you need any help with how to make use of the package, you can contact me anytime I call you via Discord.

Yours sincerely,

Glaucia Lemos

**Comment by ricardasjak** [comment]
> I may be changing the title to Part 01 and Part 02. I think it would actually avoid confusion in the textual interpretation of the developed workshops.
> 
> You can follow usage of `@microsoft/microsoft-graph-client` in that file here:
> 
> https://github.com/glaucia86/msgraph-nextjs-workshops/blob/main/demo-02/reminder-app/pages/api/getPresence.ts
> 

Hello, thank you very much for your response. I am sorry for my direct style, I am not English speaker in the end. 

Given example seems about right, I will take closer look another day. 

Consider this issue resolved.

**Comment by glaucia86** [comment]
Thank you for your feedback @ricardasjak! No problem :)

Reading your feedback and the title can cause some confusion. I will open a PR following up your advice! Thank you for your contribution about it! We really appreciate it!
